# **IMPORTING LIBRARIES**

In [4]:
import numpy as np 
import pandas as pd 

import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix, accuracy_score

# **IMPORTING DATASET**

In [5]:
dataset = pd.read_csv("/home/akanksha/Downloads/healthcare-dataset-stroke-data.csv")

In [6]:
dataset

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [7]:
dataset.describe()

id          age  hypertension  heart_disease  \
count   5110.000000  5110.000000   5110.000000    5110.000000   
mean   36517.829354    43.226614      0.097456       0.054012   
std    21161.721625    22.612647      0.296607       0.226063   
min       67.000000     0.080000      0.000000       0.000000   
25%    17741.250000    25.000000      0.000000       0.000000   
50%    36932.000000    45.000000      0.000000       0.000000   
75%    54682.000000    61.000000      0.000000       0.000000   
max    72940.000000    82.000000      1.000000       1.000000   

       avg_glucose_level          bmi       stroke  
count        5110.000000  4909.000000  5110.000000  
mean          106.147677    28.893237     0.048728  
std            45.283560     7.854067     0.215320  
min            55.120000    10.300000     0.000000  
25%            77.245000    23.500000     0.000000  
50%            91.885000    28.100000     0.000000  
75%           114.090000    33.100000     0.000000  
max           271.740000    97.600000     1.000000

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


# **Checking for missing value**

In [9]:
dataset.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

# **DEALING WITH CATEGORICAL DATA**

In [10]:
dataset = pd.get_dummies(data = dataset, drop_first = True)

In [11]:
dataset

id   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0      9046  67.0             0              1             228.69  36.6   
1     51676  61.0             0              0             202.21   NaN   
2     31112  80.0             0              1             105.92  32.5   
3     60182  49.0             0              0             171.23  34.4   
4      1665  79.0             1              0             174.12  24.0   
...     ...   ...           ...            ...                ...   ...   
5105  18234  80.0             1              0              83.75   NaN   
5106  44873  81.0             0              0             125.20  40.0   
5107  19723  35.0             0              0              82.99  30.6   
5108  37544  51.0             0              0             166.29  25.6   
5109  44679  44.0             0              0              85.28  26.2   

      stroke  gender_Male  gender_Other  ever_married_Yes  \
0          1            1             0                 1   
1          1            0             0                 1   
2          1            1             0                 1   
3          1            0             0                 1   
4          1            0             0                 1   
...      ...          ...           ...               ...   
5105       0            0             0                 1   
5106       0            0             0                 1   
5107       0            0             0                 1   
5108       0            1             0                 1   
5109       0            0             0                 1   

      work_type_Never_worked  work_type_Private  work_type_Self-employed  \
0                          0                  1                        0   
1                          0                  0                        1   
2                          0                  1                        0   
3                          0                  1                        0   
4                          0                  0                        1   
...                      ...                ...                      ...   
5105                       0                  1                        0   
5106                       0                  0                        1   
5107                       0                  0                        1   
5108                       0                  1                        0   
5109                       0                  0                        0   

      work_type_children  Residence_type_Urban  \
0                      0                     1   
1                      0                     0   
2                      0                     0   
3                      0                     1   
4                      0                     0   
...                  ...                   ...   
5105                   0                     1   
5106                   0                     1   
5107                   0                     0   
5108                   0                     0   
5109                   0                     1   

      smoking_status_formerly smoked  smoking_status_never smoked  \
0                                  1                            0   
1                                  0                            1   
2                                  0                            1   
3                                  0                            0   
4                                  0                            1   
...                              ...                          ...   
5105                               0                            1   
5106                               0                            1   
5107                               0                            1   
5108                               1                            0   
5109                               0                            0   

      smoking_status_smokes  
0 

# **SPLITTING DATA INTO X AND Y**

In [12]:
y = dataset.iloc[:,6].values
dataset = dataset.drop(["stroke"], axis = 1)
x = dataset.iloc[:,1:].values

# **DEALING WITH MISSING VALUE**

In [13]:
imputer = KNNImputer(missing_values = np.nan, n_neighbors = 3)
x = imputer.fit_transform(x)

le = LabelEncoder()
y = le.fit_transform(y)

# **SPLITTING DATA INTO TRAINING AND TEST SET**

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 1)

# **TESTING LOGISTIC REGRESSION MODEL**

In [15]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

/home/akanksha/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
y_pred_lr = lr.predict(x_test)

# **TESTING DECISION TREE CLASSIFIER**

In [17]:
dtc = DecisionTreeClassifier(criterion = "gini", max_depth = 10, random_state = 1)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, random_state=1)

In [18]:
y_pred_dtc = dtc.predict(x_test)

# **TESTING RANDOM FOREST CLASSIFIER**

In [19]:
rfc = RandomForestClassifier(n_estimators = 10, criterion = "gini", max_depth = 10, random_state = 1)
rfc.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=10, random_state=1)

In [20]:
y_pred_rfc = rfc.predict(x_test)

# **TESTING SUPPORT VECTOR CLASSIFIER**

In [21]:
svc = SVC(random_state = 1)
svc.fit(x_train, y_train)

SVC(random_state=1)

In [22]:
y_pred_svc = svc.predict(x_test)

# **TESTING K NEAREST NEIGHBORS**

In [23]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = "minkowski")
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [24]:
y_pred_knn = knn.predict(x_test)

# **CHECKING THE ACCURACY OF DIFFERENT MODELS**

**LOGISTIC REGRESSION**

In [25]:
cm_lr = confusion_matrix(y_test, y_pred_lr)
print(cm_lr)
accuracy_score(y_test, y_pred_lr)

[[962   0]
 [ 60   0]]


0.9412915851272016

**DECISION TREE CLASSIFIER**

In [26]:
cm_dtc = confusion_matrix(y_test, y_pred_dtc)
print(cm_dtc)
accuracy_score(y_test, y_pred_dtc)

[[924  38]
 [ 52   8]]


0.9119373776908023

**RANDOM FOREST CLASSIFIER**

In [27]:
cm_rfc = confusion_matrix(y_test, y_pred_rfc)
print(cm_rfc)
accuracy_score(y_test, y_pred_rfc)

[[954   8]
 [ 60   0]]


0.9334637964774951

**SUPPORT VECTOR CLASSIFIER**

In [28]:
cm_svc = confusion_matrix(y_test, y_pred_svc)
print(cm_svc)
accuracy_score(y_test, y_pred_svc)

[[962   0]
 [ 60   0]]


0.9412915851272016

**K NEAREST NEIGHBORS**

In [29]:
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
accuracy_score(y_test, y_pred_knn)

[[957   5]
 [ 60   0]]


0.9363992172211351

# **Logistic Regression and SVC have same accuracy which is the highest among all the models**